M48
; DRILL file {KiCad 8.0.8} date 2025-02-27T16:48:45+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-27T16:48:45+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
%
G90
G05
T1
X1.7309Y-1.0489
X1.7309Y-1.1289
X1.9309Y-1.0889
T2
X1.2598Y-1.0237
X2.1259Y-2.4409
M30
